Repository awslabs/aws-embedded-metrics-python, pull requests merged in 2022-08, with the labels that each got.

#85 Disallow duplicate dimension sets
  aws_embedded_metrics/logger/metrics_context.py
  tests/logger/test_metrics_context.py
Labels: bug

#90 Move buildspecs inline with project
  aws_embedded_metrics/logger/metrics_context.py
  aws_embedded_metrics/logger/metrics_logger.py
  buildspecs/buildspec.canary.yml
  buildspecs/buildspec.release.prod.yml
  buildspecs/buildspec.release.test.yml
  buildspecs/buildspec.yml
  tests/environment/test_environment_detector.py
  tests/environment/test_lambda_environment.py
  tests/logger/test_metrics_context.py
  tests/serializer/test_log_serializer.py
Labels: chore

#89 Support clear custom dimensions and related enhancements
  README.md
  aws_embedded_metrics/logger/metrics_context.py
  aws_embedded_metrics/logger/metrics_logger.py
  tests/logger/test_metrics_logger.py
Labels: enhancement
